---
apiVersion: v1
kind: Namespace
metadata:
  name: http-egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-egress
  namespace: http-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-egress
  template:
    metadata:
      labels:
        app: http-egress
    spec:
      containers:
      - name: http-egress
        image: buoyantio/bb:latest
        args: ["http-egress", "--h1-server-port", "8081", "--url", "https://versioncheck.linkerd.io/version.json"]
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: http-egress-svc
  namespace: http-egress
spec:
  selector:
    app: http-egress
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-egress-gateway
  namespace: http-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-egress-gateway
  template:
    metadata:
      labels:
        app: http-egress-gateway
    spec:
      containers:
      - name: http-to-http-egress
        image: buoyantio/bb:latest
        args: ["point-to-point-channel", "--h1-server-port", "8080", "--h1-downstream-server", "http://http-egress-svc:8081"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-egress-gateway-svc
  namespace: http-egress
spec:
  selector:
    app: http-egress-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
